### ISSUE TITLE
Zifencei shouldn't be mandatory for small embedded cores

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-profiles#1]
Zifencei has been too expensive for us to implement, for the exact reason it was removed from the base ISA:

_In particular, for designs that have an incoherent instruction cache and an incoherent data cache, or where the instruction cache refill does not snoop a coherent data cache, both caches must be completely flushed when a FENCE.I instruction is encountered._

Therefore I request that Zifencei is not made mandatory, because it is not cost effective for us to implement it as specified.

**Comment by kasanovic** [comment]
Agreed, and was dropped from the M profiles, though current text focuses on A profiles.

**Comment by kasanovic** [comment]
Closing, as not part of current profile.
