### ISSUE TITLE
Is there any test suite to get the profile coverage of RISC-V machines? 

### ISSUE THREAD

**Issue by lutong-z** [riscv/riscv-profiles#101]

**Comment by jjscheel** [comment]
@lutong-z, the ACT (Architectural Compatibility Tests) provide tests by extensions and we presently are investigating how best to tie in profiles.  If you have interest in this discussion you might join the [ACT SIG](https://lists.riscv.org/g/sig-arch-test)

**Comment by kasanovic** [comment]
Closing, as the ACT group is where this is handled. Also, new CSC committee is handling platform certification.
