### ISSUE TITLE
inconsistent titling

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#108]
you say:
"The following privileged extensions are mandatory, and are also mandatory in RVA23S64.

Ss1p13 Privileged Architecture version 1.13.

Note
Ss1p13 supersedes Ss1p12 but is not yet ratified.
The following privileged extensions were also mandatory in RVB22S64"

seems like the language in the last sentence should mimic the first as things such as napot are mandatory in both.

**Comment by kasanovic** [comment]
"are" is present tense for RVA23, "were" is past tense for RVA22.
