### ISSUE TITLE
Sstc specification

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-profiles#115]
The public review document is this one:

https://drive.google.com/file/d/1m84Re2yK8m_vbW7TspvevCDR82MOBaSX/view?usp=sharing

The link given here is:

https://github.com/riscv/riscv-time-compare which has one spec release: https://github.com/riscv/riscv-time-compare/releases/download/v0.5.4/Sstc.pdf

at first glance the text looks the same, but is it? What's the correct reference?

**Comment by aswaterman** [comment]
I was just recently discussing this with @gfavor.  We think we simply forgot to publish an updated spec that incorporated the public review feedback, and so neither is correct.  We'll try to correct this oversight ASAP.

**Comment by aswaterman** [comment]
The public review feedback was incorporated in this commit: https://github.com/riscv/riscv-time-compare/commit/8f20ff9e94c8db66149237fc6055850190b68842

The HEAD of the main branch now indicates that public review has completed (but it doesn't indicate ratification).
