### ISSUE TITLE
svade and svadu

### ISSUE THREAD

**Issue by davidharrishmc** [riscv/riscv-profiles#119]
The RVA23S64 profile indicates that SVADE is required and SVADU is optional.  If I understand these two, SVADE page faults for the A/D bits, and SVADU handles them in hardware.  

As presently worded, it seems that they are incompatible, and requiring SVADE prohibits the use of SVADU.  Given that SVADU is an option, what does it mean for SVADE to be required?  

This also carries back to the RVA22 profiles, in which SVADE is required.  I had interpreted that to mean that SVADU is prohibited in RVA22.  Is that the intent, or am I misinterpreting SVADE?

Thank you,
David Harris

**Comment by kasanovic** [comment]
Svadu is an extension over baseline Svade behavior, with an enable bit (menvcfg.ADUE) to turn on hardware A/D bit handling, so they are compatible.
In RVA22, we did not sanction use of  hardware A/D updates without the enable as this would be incompatible with baseline Svade.
