### ISSUE TITLE
Is Ssu64xl mandatory or optional in RVA22?

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-profiles#122]
In RVA22 profile [changelog](https://github.com/riscv/riscv-profiles/blob/main/profiles.adoc#changes-since-public-review-version-08), it said `Fixed Ssu64xl to make supporting UXL=64 mandatory`. However, the extension still locates at [RVA22S32 optional](https://github.com/riscv/riscv-profiles/blob/main/profiles.adoc#623-rva22s64-optional-extensions) after ratification. In RVA23 profile, it said Ssu64xl is also mandatory in RVA22S32 ([link](https://github.com/riscv/riscv-profiles/blob/main/rva23-profile.adoc#rva23s64-mandatory-extensions)).

**Comment by kasanovic** [comment]
has been fixed
