### ISSUE TITLE
Za64rs clarification

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-profiles#126]
`Za64rs: Reservation set size of 64 bytes`

`Za64rs Reservation sets are contiguous, naturally aligned, and a maximum of 64 bytes.`

these are the two statements for Za64rs. Can the first one be changed to

`Za64rs: Maximum reservation set size of 64 bytes`

to clarify that it's not a fixed size but an upper limit?

**Comment by aswaterman** [comment]
Will fix.
