### ISSUE TITLE
RVA23: Zjpm - which extensions and PMLENs are required

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-profiles#130]
RVA23U64 mandates support of Zjpm, but doesn't specify which extensions (Ssnpm, Smnpm, Smpm) and PMLEN mask bit widths (7, 16) are required.  The Zjpm spec leaves these decisions up to implementations or profiles:

```
Profiles and implementations may choose to support an arbitrary subset of these extensions and must define valid ranges for
their corresponding values of PMLEN.
```

To avoid leaving this up to implementations (which could result in fragmentation), the profile should explicitly specify the extensions and the PMLENs required for Bare, Sv48, Sv57.

I think that many will be wondering if PMLEN=16 will be mandated for Sv57 as it ends up masking bits in the virtual address space (VBITs).

**Comment by aswaterman** [comment]
I agree we shouldn't leave this up to the imagination.  The ARC's recommendation was to mandate PMLEN=7 only (leaving PMLEN=16 support as an option) on the basis that we want to allow Sv57 without the circuit-delay implications of significant VA bits intersecting with masked points.  To put a stake in the ground, I'll update the spec accordingly (while noting our recommendation might not be the final word on this topic).
