### ISSUE TITLE
Do Ziccrse/Ziccamoa/Za64rs/Za128rs imply A?

### ISSUE THREAD

**Issue by lukel97** [riscv/riscv-profiles#139]
The Ziccrse/Ziccamoa/Za64rs/Za128rs extensions take advantage of features from the A extension, namely reservation sets and AMOArithmetic operations. However I couldn't find any mention in the specification that these extensions imply/depend on A. 

Is it possible for a processor to support one of these extensions without A?

**Comment by aswaterman** [comment]
I think it is valid, albeit useless, to have e.g. Ziccrse without Zalrsc/A.  So it is fine that these extensions do not have any implications.

**Comment by lukel97** [comment]
That makes sense, thanks for the clarification.
