### ISSUE TITLE
It is not recommended to make sstatus.UXL!=64 an unsupported extension

### ISSUE THREAD

**Issue by dennisyyz** [riscv/riscv-profiles#15]
The profile should not only consider users who natively build new systems on RISC-V, but should also consider the needs of users who have migrated from other platforms. At present, a considerable number of users in the IoT market are trying to migrate from 32-bit low-cost application processor systems such as Cortex-A7 to RISC-V. They want to still maintain (non-binary) compatibility with legacy 32-bit user mode code. This not only requires hardware to support 32-bit user mode, but also requires RISC-V linux to support compat mode. sstatus.UXL!=64 becoming an unsupported extension will limit risc-v Linux mainline support for compat mode, which will adversely affect these users.
Therefore it is not recommended to make sstatus.UXL!=64 an unsupported extension.

**Comment by aswaterman** [comment]
Your argument is that folks will have an easier time porting their code from AArch32 to RV32.  That's bunk.  Once you've ported the code to a new ISA, it hardly matters whether it's a 32-bit or 64-bit ISA (unless the code is very poorly written).
