### ISSUE TITLE
Main memory supports vector storage instructions.

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-profiles#155]
While it stands to reason that main memory must support vector storage operations, this feature implicitly indicates that there shall be  no expectation that vector storage instructions must access IO memory. Such support may be mandated in a standard profile or may be implementation specific.

The primary concern here is not access to IO memory per se, but rather to non-idempotent memory. Vector instruction support of non-idempotent memory can create undue complexities in a high-performance implementation, especially in the area of segmented instructions.

**Comment by kasanovic** [comment]
Behavior of I/O or other non-idempotent memory is a platform issue, so out of scope for profile specs.
