### ISSUE TITLE
RVM23 comment: Zimop Zcmop can be NOPs?

### ISSUE THREAD

**Issue by ubc-guy** [riscv/riscv-profiles#163]
RVM23 says Zimop and ZCmop can be implemented as NOPs. Is this true?

These specs require writing 0 to rd.

**Comment by ved-rivos** [comment]
The comment under the Zcmop applies only to Zcmop and, unlike Zimop, C.MOP.n does not write to any register.

**Comment by ved-rivos** [comment]
This was addressed in https://github.com/riscv/riscv-profiles/commit/326d29536cef08f007539015e663ac6c44e1e7be
