### ISSUE TITLE
bring this spec up  to the latest doc-specs-template

### ISSUE THREAD

**Issue by kbroch-rivosinc** [riscv/riscv-profiles#167]
including:

* add README
* add MAINTAINERS
* add CONTRIBUTING
* LICENSE update
* update build (Makefile, src dir)
* enable pre-commit (hooks and GH action)
* assuming #156 lands, and any other attribute changes in header of adoc

Won't be any content changes to spec (whitespace changes from pre-commit hooks don't count)

**Comment by aswaterman** [comment]
Agreed in principle, but the plan is to incorporate the profiles into the main ISA spec soon, and so this work will largely be discarded at that point.  I propose we do nothing for now, merge the contents into the main ISA spec, and archive this repo.

**Comment by aswaterman** [comment]
I see some of this work was completed in #168; thanks for that.  I'll close this for now for reasons mentioned in my previous comment.
