### ISSUE TITLE
Zbkx should be expansion option or required, as xperm4/xperm8 are incredibly useful for general purpose bit manipulation

### ISSUE THREAD

**Issue by camel-cdr** [riscv/riscv-profiles#180]
I noticed that the scalar crypto instructions won't be part of future profiles:

> Scalar crypto is no longer an option in RVA23U64, though the Zbc extension has now been exposed as an expansion option.

Zbc is now an expansion option, but I think Zbkx should also be one, or preferably be mandatory as it's very versatile.

Zbkx defines the xperm4 and xperm8 instructions, which receptively look up all nibbles or bytes in a 64-bit GPR.
This is incredibly useful for bit manipulation:

* Check if any bytes are zero: `xperm8(0xFF,x) == 0`
* Replicate first byte to all others: `xperm8(x,0)`
* Replicate nth byte to all others: `xperm8(x,perm8(n,0))`
* Zero all negative 8-bit integers: `y=xperm4(0xFFFFFFFF,x)&0xF0F0F0F0F0F0F0F0; (y>>4|y)&x`
* [SWAR utf8 validation](https://camel-cdr.github.io/rvv-bench-results/articles/xperm4-utf8-validation.html)

I understand that the idea is that vector cypto replaces scalar crypto, so we don't need to instructions, however as you can see above the `xperm*` instructions are useful for general purpose bit manipulation.

**Comment by kasanovic** [comment]
To be more precise, while it is not intended to include scalar crypto in future RVA profile, other profiles, such as RVB, might 
continue to include scalar crypto as an option.

It is late to add new mandatory features. Checking for "any bytes zero?" is already covered with the mandatory orc.b instruction.   The remaining operations seem of limited utility, so I can't see the need to include as mandate.
