### ISSUE TITLE
Can we say we support RVA23U64 by software emulation at higher privilege mode?

### ISSUE THREAD

**Issue by Tang-Haojin** [riscv/riscv-profiles#193]
Hi. I noticed that this document mentioned:
https://github.com/riscv/riscv-profiles/blob/f2e15b5d66988a7165e9167b50ef10d2fd03b402/src/profiles.adoc?plain=1#L207-L209

Does this mean that, for example, we can say we support zicclsm in RVA23U64 even if we do not support hardware misaligned loads or stores but can be handled by software at higher privilege mode like opensbi at M-mode?

**Comment by aswaterman** [comment]
Yes.  The definition of Zicclsm (in the RVA20 profile spec) even includes a note to this effect.  Nothing has changed about Zicclsm in RVA23.

**Comment by Tang-Haojin** [comment]
I see. Thanks a lot.
