### ISSUE TITLE
PME should be replaced with PMM regarding to the configuration of pointer masking extension(Ssnpm)

### ISSUE THREAD

**Issue by viktoryou** [riscv/riscv-profiles#195]
From ratified version of Pointer Masking extension, Ssnpm adds PMM to bits 33:32 of senvcfg & henvcfg, and Smmpm adds PMM to bits 33:32 of mseccfg. However the profile used an out-dated naming as PME, see [here](https://github.com/riscv/riscv-profiles/blob/main/src/rva23-profile.adoc?plain=1#L286). Please help to take a look.

**Comment by aswaterman** [comment]
Fixed.  Thanks for pointing this out.
