### ISSUE TITLE
use standard language

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#25]
I spoke with greg about this.

for example:

"Misaligned loads and stores may not be supported"

shouldn't this be supported optional (assuming the word may implies it may be supported too)?

if we use the language you have already defined, it becomes clearer: m, so, uo, i

**Comment by pdonahue-ventana** [comment]
"may not" should be avoided since it could be interpreted as a prohibition.  Either "might not be supported" (keeping similar language) or "may be supported" (using RFC 2119 language) or "supported/unsupported optional" (using the proper terms from the profile spec).

**Comment by aswaterman** [comment]
Definitely agreed we should favor "might not" over "may not" in general.  In this case, "Misaligned stores are supported optional" seems like the right phrasing.
