### ISSUE TITLE
Misaligned load and store instruction

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-profiles#28]
Zicclsm Misaligned loads and stores are supported (i.e., no visible trap) to main memory regions  with cacheability and coherence

**Comment by allenjbaum** [comment]
Just to be clear: this is regardless of cache line or page boundary crossing? (obviously crossing protectin boundaries may trap if the access crosses into a protected region - which is a spearate option: do sotres perform the first part before trapping?

**Comment by kasanovic** [comment]
Yes, regardless of any crossings.
The existing ISA spec describes the possible behaviors of an execution environment around misaligned traps.
