### ISSUE TITLE
RVM22 Profiles

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-profiles#3]
In [platform spec](https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.adoc#321-architecture), it suggests M platform should comply RVM22M profile. Currently, there is no RVM22 profiles in this repo. When will them be published?

**Comment by aswaterman** [comment]
We are prioritizing the development of RVA22.  We know there's demand for RVM22, and we'll get back to it once we've made major progress on RVA22.

**Comment by kasanovic** [comment]
The RVM profiles are on hold until there is sufficient enthusiasm and volunteers to drive the spec.

**Comment by henry-hsieh** [comment]
TG has proposed a draft version of RVM23 profile. IMO, the RVM22 is no longer required.
