### ISSUE TITLE
Cache line size option

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-profiles#37]
Zic64b.   64-byte cache lines

**Comment by dkruckemyer-ventana** [comment]
Cache lines? Or cache blocks? The Zicbo* extensions work on "cache blocks," but the definition was crafted to allow us to abstract the implementation of the caches, i.e. the size of a cache line in the implementation doesn't have to match the size of a cache block. In other words, we were thinking "cache block" was a software concept that could map into one or more "cache lines" in the implementation of the cache. Of course, that mapping is trivial if the size of a cache block equals the size of a cache line.

There's also some subtlety with respect to coherence management and writeback data size (and maybe even reservation sets?). Does this extension imply all of these things are uniformly 64B?

**Comment by aswaterman** [comment]
@dkruckemyer-ventana It should be "blocks", since the intent was to specify the unit handled by Zicbo*.  (And indeed the existing normative text in the profile spec uses the word "blocks".)

**Comment by cmuellner** [comment]
The Zicbo* specification mentions two different block sizes in section 2.7: 1) cache block size for management and prefetch instructions, and 2) cache block size for zero instruction. Would Zic64b imply a 64-byte cache block size for both?

**Comment by kasanovic** [comment]
Should be Zic64b. 64-byte cache blocks.

**Comment by kasanovic** [comment]
@cmuellner Yes, Zic64b implies 64-byte lines for both 1) and 2).
