### ISSUE TITLE
minor U/S typos

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-profiles#42]
Section 5.2.3 RVA20S64 Supported Optional Extensions says "RVA20U64 has one unprivileged supported option." which doesn't make sense here.  Looks like a U/S typo.

Section 6.2.1. RVA22S64 Mandatory Base says "RV64I is the mandatory base ISA for RVA22U64, including mandatory fence.tso." which again makes no sense here.  Looks like a U/S typo.

**Comment by aswaterman** [comment]
Thanks, Jim.  Since both sentences are true for both U and S profiles, I'm guessing this was copy-paste.
