### ISSUE TITLE
Entropy extension Zkr should be a supported option

### ISSUE THREAD

**Issue by grnewell** [riscv/riscv-profiles#51]
Currently Zkr is in the "RVA22U64 Unsupported Optional" list.  Shouldn't it be in the "RVA22U64 Supported Options" list, instead?  Perhaps a meeting between Profile members and Crypto TG members should be arranged to discuss this.

**Comment by aswaterman** [comment]
The rationale here was that unprivileged software will access an entropy source through a syscall (possibly via a device in the file system).  For RVA22, standard unprivileged software stacks won't directly utilize the `seed` CSR, hence "unsupported", but it's not illegal to provide them anyway (and some custom software stacks might access `seed` directly), hence "optional".

By contrast, Zkr is "supported optional" for RVA22S64, signaling our expectation that supervisor software will directly access the `seed` CSR, including to implement aforementioned syscall.
