### ISSUE TITLE
why aren't fence.tso and ecall extensions?

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#54]
from the section:

==== RVI20U32 Mandatory Base

RV32I is the mandatory base ISA for RVI20U32, and is little-endian.

The `ecall` instruction causes a requested trap to the execution
environment.

Misaligned loads and stores might not be supported.

The `fence.tso` instruction is mandatory.

**Comment by kasanovic** [comment]
ECALL is part of base ISA.  It's behavior depends on execution environment (it's an explicit environment call, hence the name)

As explained in note in doc, fence.tso is effectively a mandatory part of FENCE instruction in base ISA, but text in 2019 version of spec was not clear about this (though any legal implementation of FENCE would have also including a legal implementation of fence.tso). 2021 text update is clear about this.
