### ISSUE TITLE
what is a mandatory base vs mandatory extensions

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#55]
the following sections lists explicit  instructions and behavior. is there prose I missed explaining the wword mandatory base?

==== RVI20U32 Mandatory Base

RV32I is the mandatory base ISA for RVI20U32, and is little-endian.

The `ecall` instruction causes a requested trap to the execution
environment.

Misaligned loads and stores might not be supported.

The `fence.tso` instruction is mandatory.

**Comment by kasanovic** [comment]
Closing this issue.  Base is defined for RISC-V, and Mandatory is standard English adjective.  I think reader should assume text has regular English meaning unless specifically perverted by some RISC-V definition.
