### ISSUE TITLE
change versions from years to numbers (e.g. v1, v2, ....)

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#60]
I wanted to capture the discussion from TSC here. I felt the same way as yunsup. there are no good solutions

**Comment by kasanovic** [comment]
Absent a better proposal, I think we stick with years.

**Comment by mark-riscv** [comment]
the world is used to "vN" versions and won't feel as antiquated when
RVA2022 is implemented in 2025. I am not sure why the vN isn't a better
marketing name.

**Comment by kasanovic** [comment]
RVA22 will be implemented in 2022.
RVA23 will be implemented in 2023.
Vx will always seem antiquated when Vx+1 is available.
This argument doesn't hold for me.

**Comment by kasanovic** [comment]
No better solution appeared.
