### ISSUE TITLE
conflate supported optional and unsupported optional into optional

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#61]
This idea was floated by philip and aaron but neither had the chance to enter so I offered. I like it because it is simpler. now is the time to do it.

lets look at whaat the actions of software aree in different cases:
1. hw exists, supported optional
2. hw exists unsupported optional
3. hw doesn't exist supported optional
4. hw doesn't exist unsupported optional

for case 1 we'd like the sw to support it (e.g. context switch registers for vector) but it is still up to sw. if it can't handle it yet then it should check the ELF flag and Discovery (likley DT by that time) and not execute the binary. if it can handle it then it should do the right things.

for case 2, it behaves a lot like case 1 except a lot smaller group of implementations will likely support.

for cases 3&4 we'd like the sw not to execute binaries using the feature as opposed to running into an illegal instruction using the same method as described for case 1.

So in practicality I don't see an effective difference other than guidance which could be added in non-normative text.

It seems like a lot of complexity with very much actual impact.

am I missing something?

**Comment by adurbin-rivos** [comment]
There's the aspects of what we want SW to do, but there's also a messaging and understandability component for any consumer of the Profiles spec proper. A single optional category is easier to explain without a lot of prose. And, I assert, that what we'll see in practice is that people will support the popular optional extensions in the SW as the original intent of the 'supported optional' category.

**Comment by mark-riscv** [comment]
seems like that is a weak reason for manifesting 2 categories. It is hard
to explain to the world and again will not be treated any differently by
software. this could be handled with non-normative text. In my opinion the
names are not consistent with your intent. So a name like high priority
optional and low priority optional or strongly suggested optional and
optional (i don't like these names but you get the idea).

**Comment by kasanovic** [comment]
RVA software will treat P and V differently.   I don't understand how putting everything in a single category and then having sub-categories with effectively the same meaning as the two original categories is preferred.  We're trying to remove optionality and give direction as to what hardware and software should coalesce the ecosystem around.

**Comment by aswaterman** [comment]
I continue to support the current categorization.

The lone "optional" category fails to connote intent.  We are trying to reduce the load on software developers, and we'd rather guide them towards focusing on things we actually expect will be relevant.

"Optional with low priority" is not much of an improvement over the lone "optional" category.  It still lends the impression that work should be done on the low-priority things at some point.  In fact, it would be better that no time be spent on the "unsupported optional" category, because doing so adds extra software complexity and distracts from other software efforts.

**Comment by kasanovic** [comment]
Proposal is to drop unsupported optional and incompatible from profiles spec, which would make this issue moot.

**Comment by kasanovic** [comment]
Done with https://github.com/riscv/riscv-profiles/commit/8525de8e97911398a6750cc9489a2c295f91b6df
