### ISSUE TITLE
status of newly created extensions

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-profiles#63]
The profiles doc has a lot of extensions which I can't find documented elsewhere, such as `Svbare`.
Are these extensions going to be ratified, so they all have version numbers, or are they considered sub-extensions of existing ratified specifications? For example, `Sv39` is in the privileged ISA spec without a version number so it is considered to be sub-extension of `Ss1p12`?

Tariq

**Comment by kito-cheng** [comment]
As a RISC-V toolchain developer, I would like to having explicit version number for those new created extensions.

**Comment by kasanovic** [comment]
These will be ratified as part of the profile doc, so will follow its version number (after ratification, they shouldn't need a version number).

**Comment by aswaterman** [comment]
Closing as answered.
