### ISSUE TITLE
zifencei disposition

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#66]
in RVI20U this is optional.
in RVA20S this is mandatory
in RVA20U this is unsupported optional.
in RVA20S this is mandatory

This is an unpriv instruction.

I read the note but this a) incongruous (what would have to be there to make it useful?) and b) I did the  fence work in alpha and can't imagine the cost of repeatedly making systems calls for this feature.

even if this is the way it will be, why is RVI20U optional? I suggest whatever reason it is but RVA20U isn't be added to some non-normative text. Again it seems incongruous.

**Comment by kasanovic** [comment]
This is all how it must be, for the reasons given in the text.
The Linux port optimizes how often the calls are done.
The Zjid extension will ultimately replace Zifencei, but is not ready yet.
RVI20U is not an RVA profile, so needs to support systems assuming no OS, and Zifencei is only available mechanism for I-cache coherence.
