### ISSUE TITLE
what are RVA22U mandatory extension dispositions in RVA22S

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#67]
If there is general prose somewhere describing this I can't find it.
If there isn't can it be added.
It is somewhere, I suggesst add a reference to it at the beginning of section 6.2.
For example: Zicsr is mandatory in RVA22U but not even listed in RVA22S

**Comment by kasanovic** [comment]
At beginning of 6.2.2:
"The RVA22S64 mandatory unprivileged extensions include all the mandatory unprivileged extensions in RVA22U64"
