### ISSUE TITLE
Clarification: `Ssu64xl`

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-profiles#75]
This is a comment for public review.

1.  Clarify whether `Ssu64xl` is a new extension name
2.  Clarify exact property of `Ssu64xl`
3.  Wrong assumption on `Ssu64xl` notes

# 1. Extension Name? 

It seems easy.  Considering [Specification Status](https://wiki.riscv.org/display/HOME/Specification+Status), it *is* an extension.
In my other pull request (#76), it assumes that `Ssu64xl` is an extension.

# 2. Property of `Ssu64xl`

> `sstatus.UXL`=64

is a simple description but it seems too simple so that it might leave some ambiguity.  Others look good but this one (`Ssu64xl`) needs some clarification.

For instance, following sentence feels okay to me (I'm not a native English speaker so better text (if any) should be placed instead).

> `sstatus.UXL`=64 (`0b10`) must be legal.

# 3. Wrong assumption on Notes

>  This field will be 0 if UXL feature is not implemented.

On RV64 with U-mode, this field cannot be zero (it can be on RV32 and RV64 without U-mode) because `UXL` is a WARL field (representing current `UXLEN`) on such systems.  Either "0" or "UXL feature is not implemented" should be fixed or we should clarify the statement further.

Quoting the RISC-V ISA Privileged Architecture 1.11 (pretty much the same as 1.12):
> For RV64 systems, the `SXL` and `UXL` fields are WARL fields that control the value of `XLEN` for S-mode and U-mode, respectively.

> For RV32 systems, the `SXL` and `UXL` fields do not exist, and `SXLEN`=32 and `UXLEN`=32.

> For RV64 systems, if U-mode is not supported, then `UXL` is hardwired to zero. Otherwise, it is a WARL field that encodes the current value of `UXLEN`.

**Comment by aswaterman** [comment]
Yes, I agree the claim "The field will be 0 if UXL feature is not implemented" is inconsistent with the priv spec.  The field must be hardwired to 2 if U-mode is implemented and only RV64 is supported.
