### ISSUE TITLE
Ssptead name

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-profiles#81]
Why does Ssptead use "s" as the second letter?  In contrast, the option for hardware updates is [Svadu](https://github.com/riscv/riscv-svadu) which uses "v" as the second letter.  Since these relate to virtual memory, it seems like the latter is correct and that Ssptead should be Svptead.

See also the long-languishing https://github.com/riscv/riscv-isa-manual/pull/688 which (possibly with appropriate tweaks) would help clarify extension names.

**Comment by aswaterman** [comment]
Seems like Sv would be the more appropriate prefix here as well.

**Comment by a4lg** [comment]
Does this apply to `Ssccptr` as well?
It seems, it is also related to hardware-based virtual memory system.

**Comment by aswaterman** [comment]
`Ssccptr` seems appropriate to me as-is, because it's a property of physical memory, not virtual.

**Comment by kasanovic** [comment]
Renamed again to Svade to be more consistent with Svadu extension name.
