### ISSUE TITLE
is Zbc required is RVA22U?

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-profiles#83]
Just watching Krte's presentation at the RISC-V summit and he said Zba/b/c/s are all mandatory.

This page doesn't list Zbc as mandatory, it also seems to be listed as a crypto scalar extension which is surprising.

Can the status of Zbc be clarified please?

**Comment by aswaterman** [comment]
I think this might've been a slip of the tongue: my understanding is that the plan hasn't changed, and only Zba/b/s are mandatory.

**Comment by tariqkurd-repo** [comment]
can we confirm? if so I'll close the issue

**Comment by aswaterman** [comment]
I’ll just close this, as I’ve found no written evidence.
