### ISSUE TITLE
RVA23: on behalf of alibaba, they feel the family description is not robust enough

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-profiles#96]
whne they read "application processors running rich operating systems" they assumed it would also target IOT devices running linux.

I suggest some additional wording like: application processors running rich operating systems running on a desktop or greater capable chip

**Comment by asb** [comment]
I think some kind of clarification makes sense, but I'd be wary of using the term "desktop" given the high performance requirements of modern mobile phone SoCs.
