### ISSUE TITLE
Will RVA23 include Zbkb and/or Zbkx?

### ISSUE THREAD

**Issue by sofia-snow** [riscv/riscv-profiles#97]
I noticed that vector crypto is optional in RVA23. This was curiously mentioned alongside "removing" scalar crypto. Does this mean that the vector crypto extension does not imply the scalar crypto extension?

In either case, does the scalar crypto, or the vector crypto extension imply either Zbkb or Zbkx?

Does the vector crypto extension imply the vector versions of these?

**Comment by kasanovic** [comment]
Vector crypto does not imply scalar crypto.

The specific extension implications are in the specs.
