### ISSUE TITLE
Drop RVA23 profile from 1.0 tarbal

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-profiles#99]
My understanding is only RVI20, RVA20, RVA22 has ratified, but seems the tarball has also including `rva23-profile.adoc`, and does it possible to mention that on the release page? or maybe adding a PDF to reduce the potential confusion?

https://github.com/riscv/riscv-profiles/releases/tag/v1.0

**Comment by kasanovic** [comment]
These will all be rolled into the main ISA document after RVA23 is ratified.
